# Konfiguracja Railway
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
nodejs-version = "18"

[service]
memory_limit = "4096"
memory_request = "2048"

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096" 