# Plik konfiguracyjny dla Railway
# Dokumentacja: https://docs.railway.app/guides/railway-toml

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "echo 'Zmienne środowiskowe podczas budowania:' && env | grep -E '^(GOOGLE_|NEXTAUTH_|DATABASE_)' || echo 'Brak zmiennych środowiskowych'"

[deploy]
# Nie restartuj kontenera natychmiast po błędzie (pozwoli to na zebranie logów)
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/auth/test-google-config"
healthcheckTimeout = 100
healthcheckInterval = 30

# Railway może mieć problemy z dużymi kontenerami
# Ustawiamy limity zasobów
numReplicas = 1

# Upewnij się, że te zmienne są ustawione jako domyślne
# Nie używaj wartości domyślnych z pliku .env.production
[deploy.env]
PORT = "3000"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Te zmienne muszą być ustawione w Railway:
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - NEXTAUTH_URL
# - NEXTAUTH_SECRET
# - DATABASE_URL 