[build]
builder = "ubuntu-nodejs"
buildCommand = "yarn && yarn prisma generate && NEXT_PUBLIC_RAILWAY_ENVIRONMENT=production NODE_OPTIONS='--max-old-space-size=4096' yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
memory_limit = "4096"
memory_request = "2048"
cpu_limit = "2"
cpu_request = "1"

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096" 