# Plik konfiguracyjny dla Railway
# Dokumentacja: https://docs.railway.app/guides/railway-toml

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Nie restartuj kontenera natychmiast po błędzie (pozwoli to na zebranie logów)
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/check-env"
healthcheckTimeout = 100
healthcheckInterval = 30

# Railway może mieć problemy z dużymi kontenerami
# Ustawiamy limity zasobów
numReplicas = 1

[deploy.env]
PORT = "3000"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 